### ISSUE TITLE
No access to created store

### ISSUE THREAD

**Issue by andris-silis** [redux-things/redux-actions-assertions#24]
Some tests need access to dispatch, e.g. when testing if the right URLs are fetched. 

Could be convenient to use store created by `redux-actions-assertions` instead of creating new one.

```javascript
const fetchSpy = sinon.spy();
mock(window.fetch, fetchSpy);

store.dispatch(fetchData()).then(() => {
  expect(fetchSpy).to.have.been.calledWith('/api/data');
}).then(done).catch(done);

```

**Comment by dmitry-zaets** [comment]
Right now you are forced to use `done` callback, which not allows you to do actions after assertion and this is not flexible.
We can solve it by returning promise from assertions.
Then you will be able to perform:
```javascript
return expect(fetchData())
  .toDispatchActions(expectedActions)
  .then(() => {
    expect(fetchSpy).to.have.been.calledWith('/api/data');
  });
```

**Comment by dmitry-zaets** [comment]
Implemented with https://github.com/redux-things/redux-actions-assertions-js/pull/2
