### ISSUE TITLE
ES6 import empty

### ISSUE THREAD

**Issue by adamyonk** [redux-things/redux-actions-assertions#25]
I'm seeing this when I try to import assertions:

```javascript
import assertions from 'redux-actions-assertions'
console.log(assertions) // => null

import { assertions } from 'redux-actions-assertions'
console.log(assertions) // => {}
```

Am I doing something wrong?

**Comment by adamyonk** [comment]
This must have something to do with my webpack setup, if I `require` through the node REPL, everything seems to be there.

**Comment by dmitry-zaets** [comment]
I will check in a moment.

**Comment by dmitry-zaets** [comment]
Potentially could be a problem with `export from` statement.

**Comment by dmitry-zaets** [comment]
Thanks for reporting!

**Comment by dmitry-zaets** [comment]
@adamyonk can you, please give versions of node, babel and webpack that you are using?

**Comment by adamyonk** [comment]
node 6.2.0
babel-core 6.14.0
babel-loader 6.2.5
babel-polyfill 6.13.0
webpack 2.1.0-beta.22

**Comment by dmitry-zaets** [comment]
Will be fixed with https://github.com/redux-things/redux-actions-assertions-js/pull/4

**Comment by dmitry-zaets** [comment]
Should be fixed in v.1.2.1.
@adamyonk  Can you please test it?

**Comment by dmitry-zaets** [comment]
I've tested it, works now.
Thanks for reporting a bug!

**Comment by adamyonk** [comment]
Hm, I installed 1.2.1 and I'm seeing this:

```javascript
import rootReducer from 'reducers'
import { assertions, buildInitialStoreState, registerInitialStoreState, registerMiddlewares } from 'redux-actions-assertions'
registerMiddlewares([thunk])
registerInitialStoreState(buildInitialStoreState(rootReducer))
console.log('/////////////////////////////')
console.log(JSON.stringify(registerInitialStoreState))
console.log(JSON.stringify(buildInitialStoreState))
console.log(JSON.stringify(registerMiddlewares))
console.log(JSON.stringify(assertions))
console.log(JSON.stringify(main))
console.log('/////////////////////////////')
```

Outputs:
```javascript
/////////////////////////////



{}

/////////////////////////////
```

Is there anything other info I can provide to help debug?

**Comment by dmitry-zaets** [comment]
JSON.strigify will not show much.
You can check with:
```
console.log(registerInitialStoreState);
console.log(buildInitialStoreState);
console.log(registerMiddlewares);
console.log(Object.keys(assertions));
```

But the best way will be to share a setup code, so I can reproduce it.

**Comment by dmitry-zaets** [comment]
If this code haven't throw an exception, that import works ok:
```javascript
registerMiddlewares([thunk])
registerInitialStoreState(buildInitialStoreState(rootReducer))
```
Please verify that assertions object is not empty, buy checking keys: `console.log(Object.keys(assertions));` or by just asserting something.

**Comment by adamyonk** [comment]
Ah, I was using a tap output, so I was trying to stringify to avoid [Object object] output. :P 1.2.1 does correct the empty import issue. Thank you!
