### ISSUE TITLE
Tape support

### ISSUE THREAD

**Issue by adamyonk** [redux-things/redux-actions-assertions#28]
I can get the tests working with something like this:

```javascript
test('someThunk', (t) => {
  registerMiddlewares([thunk])
  registerInitialStoreState(buildInitialStoreState(rootReducer))

  const expectedActions = [
    actions...
  ]

  const initialState = {
    ...
  }

  assertions.toDispatchActionsWithState(
    initialState,
    someAction(),
    expectedActions,
    t.end
  )
})
```

This kind of works, because if something goes wrong in `toDispatchActionsWithState`, tape catches the thrown error and fails the test run, but it doesn't count the test in the tape output when it's passing, because you never actually assert anything with tape (`t.equal`, `t.deepEqual`, etc.). If there was some way to get the output actions of `toDispatchActionsWithState`, I could do some assertion like this:

```javascript
  const expectedActions = [
    actions...
  ]

  const initialState = {
    ...
  }

  assertions.toDispatchActionsWithState(
    initialState,
    someAction(),
    expectedActions,
    (actualActions) => {
      t.deepEqual(
         actualActions,
         expectedActions,
         'should run the correct actions'
      )
    }
  )
```

I saw that you can pass a `done` _and_ `fail` function in, but I think that would leave us in the same boat here. I'm not sure that an actual tape integration is necessary, if there is a way to get at the array of the actions that were dispatched and to not have a mismatch throw an error (so it could be handled by `equal`, `deepEqual`, and friends.

**Comment by dmitry-zaets** [comment]
Can you please try to pass `tape.pass` and `tape.fail` as done and error callbacks into assertion? Should work in that case.

**Comment by dmitry-zaets** [comment]
You can use `t.end` in `then` block, or you can use `t.plan(n)` which is more natural for tape.

**Comment by dmitry-zaets** [comment]
After all, would be good to add Tape to list of supported frameworks and add doc for it.

**Comment by adamyonk** [comment]
I'd be happy to start a PR, if that would be helpful to you.

**Comment by dmitry-zaets** [comment]
@adamyonk Sure!
would be also good to include tape into the project and by analogy, create tests with tape as we have with other frameworks.

**Comment by dmitry-zaets** [comment]
- [ ] Add Tape to Readme
- [ ] Add Tape docs page with usage examples
- [ ] Add Tests for tape
- [ ] Add Tests with tape as a step to npm test
