### ISSUE TITLE
Add Jest support

### ISSUE THREAD

**Issue by dmitry-zaets** [redux-things/redux-actions-assertions#33]
- [x]  Add [Custom Matchers](https://facebook.github.io/jest/docs/api.html#extending-jest-matchers) for Jest:
  - [x] toDispatchActions
  - [x] not.toDispatchActions and/or toNotDispatchActions
  - [x] withState
- [x]  Add Tests for Jest
- [x]  Add Tests with Jest as a step to npm test
- [x]  Add Jest to Readme
- [x]  Add Jest docs page with usage examples

**Comment by adamyonk** [comment]
I don't have time to do this right now, so leaving this here as a quick tip for anyone who needs it working ASAP:

```javascript
  it('should run the correct actions', () => {
    return assertions.toDispatchActionsWithState(
      state,
      action(arg),
      expected,
      // done will be a thrown error if actions don't match expected
      done => expect(done).toBeUndefined()
    )
  })
```
