### ISSUE TITLE
Problems with Jest matchers

### ISSUE THREAD

**Issue by adamyonk** [redux-things/redux-actions-assertions#37]
@giuband thanks for adding the jest matchers!

I was just trying them out and it looks to me like jest matchers are always passing no matter what. This test:

```javascript
  it('should run the correct actions', () => {
    expect(deleteTagSet(tagSet))
      .toDispatchActionsWithState(
        { currentTagSet: { ...tagSet }, tagSets: [], options: { queryStringControl: false } },
        expected,
        done => console.log(done)
      )
  })
```

results in

![messages image 2856963559](https://cloud.githubusercontent.com/assets/33258/22110257/ad8f4b2c-de20-11e6-85ff-15899705a81b.png)

but changing the expected actions array to something bogus like
```javascript
  it('should run the correct actions', () => {
    expect(deleteTagSet(tagSet))
      .toDispatchActionsWithState(
        { currentTagSet: { ...tagSet }, tagSets: [], options: { queryStringControl: false } },
        expected.concat({ type: 'bogus'}),
        done => console.log(done)
      )
  })
```

results in

![screen shot 2017-01-19 at 8 25 35 am](https://cloud.githubusercontent.com/assets/33258/22110343/fe27f912-de20-11e6-89e8-3e42a4b9b0e6.png)

It seems like the assertions are being run and passing/failing correctly, but the promise isn't being handed back correctly to jest, and it's marking every test as passing.

**Comment by giuband** [comment]
Hi @adamyonk, at first sight I'd say you are missing the `done` callback parameter.
Could you please try changing:
```
it('should run the correct actions', () => {
```
into:
```
it('should run the correct actions', (done) => {
```
and replace `done => console.log(done)` with simply `done` in the parameters of `toDispatchActionsWithState`.

Let me know if this helps.

**Comment by adamyonk** [comment]
@giuband gah, that was it, thanks!
