### ISSUE TITLE
'Unhandled promise rejection'

### ISSUE THREAD

**Issue by TristanWright** [redux-things/redux-actions-assertions#38]
My tests are passing but after running I get a wall of:

>  ```'Unhandled promise rejection', Error{config: Object{adapter: function xhrAdapter(config) { ... }, transformRequest: Object{0: ...}, transformResponse: Object{0: ...}, timeout: 60000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: function validateStatus(status) { ... }, headers: Object{Accept: ...}, baseURL: 'http://test:80/api/v1', method: 'get', cancelToken: CancelToken{promise: ...}, url: 'http://test:80/api/v1/taskflows/574c9d900640fd6e133b4b57/tasks', data: undefined}, response: undefined}```

I'm not sure this is a bug but something with how I'm using redux-actions-assertions to test actions with async calls.

**Comment by dmitry-zaets** [comment]
Looks like you are not mocking your API calls properly.

**Comment by TristanWright** [comment]
Figured it out, all on my side. Thanks again for maintaining this library :)
